# Generated by Django 5.2.17 on 2026-10-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.RemoveField(
            model_name="event",
            name="updated_at",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-timestamp", "-id"], name="core_event_ts_id_desc_idx"),
        ),
    ]
