# Generated by Django 5.2.9 on 2025-12-20 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="event",
            new_name="core_event_distinc_3cac99_idx",
            old_name="core_event_distinc_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="core_event_event_n_0ddde0_idx",
            old_name="core_event_event_n_idx",
        ),
    ]
